### ISSUE TITLE
Parsley Validator

### ISSUE THREAD

**Issue by MichiBeck** [einpraegsam/powermailextended#2]
Hi, 

is it possible to change this file causing a ParsleyValidator deprecated message:
**powermailextended/Resources/Public/JavaScripts/ZipValidation.js**

to:

_window.Parsley.addValidator(
	'custom100', function (value, requirement) {
		if (value >= 80000) {
			return true;
		}
		return false;
	}, 32)
	.addMessage('en', 'custom100', 'Error');_

Thank you in advance!

**Comment by einpraegsam** [comment]
Thx, I pushed a fix
