### ISSUE TITLE
[Feature] Sending HTML mails with images

### ISSUE THREAD

**Issue by benjaminpick** [einpraegsam/powermailextended#3]
Hi,

I have created a SendMailService-Extension in order to send HTML mails with images (for the footer signature). It parses the email HTML for `<img` tags and tries to embed them from the webserver instead of leaving them hotlinked. 

Are you interested to have it merged here?

**Comment by einpraegsam** [comment]
I'm not sure. This extension is just an example extension how someone could extend powermail. The most needed cases should be described.
How many changes are needed for the embeded images?

**Comment by benjaminpick** [comment]
I have posted the class for reference there:
https://gist.github.com/benjaminpick/b0c8c4d9a0e9c219413b4c022db6ddcf

We could keep it in a seperate file by renaming the class and adding a second signal.

**Comment by einpraegsam** [comment]
I think it's better to have it not in the example extension. Thx anyways for your ideas!
