### ISSUE TITLE
Any updates needed for custom field properties in T3 >=9?

### ISSUE THREAD

**Issue by deflektor-de** [einpraegsam/powermailextended#5]
Hi there!

I can't get this example extension to work in TYPO3 >=9. I want to extend form fields with custom properties. There's no error, but the fluid-markers are not replaced.

The recommended code for new field properties in the powermail docs also seams to base on this code here. Are there any updates needed for the current versions 9 of T3?

**Comment by phvt** [comment]
In 9.5, this TypoScript should work (adding the "columns" property to mapping):

`config.tx_epbase.persistence.classes {
    In2code\Powermailextended\Domain\Model\Field {
        mapping {
            tableName = tx_powermail_domain_model_field
            columns.tx_powermailextended_powermail_text.mapOnProperty = txPowermailextendedPowermailReadonly
        }
    }
}`

Docs: https://docs.typo3.org/m/typo3/book-extbasefluid/9.5/en-us/6-Persistence/4-use-foreign-data-sources.html?highlight=maponproperty &
https://docs.typo3.org/m/typo3/book-extbasefluid/9.5/en-us/b-ExtbaseReference/Index.html#typoscript-configuration

However, a breaking change in TYPO3 10.0 moved the configuration of this mapping to PHP:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html?highlight=maponproperty

Updated docs:
https://docs.typo3.org/m/typo3/book-extbasefluid/master/en-us/6-Persistence/4-use-foreign-data-sources.html

Good luck!

**Comment by deflektor-de** [comment]
Ok, the typoscript-tweak seams to be updated now in Powermail docs as well as in this extension.
Additional you need to add the extended FormRepository of your extension to extbase objects.
